### ISSUE TITLE
Execute server integration tests inside docker image 

### ISSUE THREAD

**Issue by nicoxx** [gator-life/gator.life#96]
some issues happens to production whereas integrations tests are ok because environment is not exactly the same

**Comment by nicoxx** [comment]
exemple of issue only detected with docker image: nltk missing

Traceback (most recent call last):
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vmagent/app/server/handlers.py", line 82, in register
    user = USER_CREATOR.create_user_in_db(email, interests, password, DAL)
  File "/home/vmagent/app/server/structinit.py", line 20, in create_user_in_db
    profile = self._profile_initializer.get_new_profile(interests)
  File "/home/vmagent/app/server/structinit.py", line 44, in get_new_profile
    words_this_sentence = nltk.word_tokenize(sentence)
  File "/env/local/lib/python2.7/site-packages/nltk/tokenize/__init__.py", line 106, in word_tokenize
    return [token for sent in sent_tokenize(text, language)
  File "/env/local/lib/python2.7/site-packages/nltk/tokenize/__init__.py", line 90, in sent_tokenize
    tokenizer = load('tokenizers/punkt/{0}.pickle'.format(language))
  File "/env/local/lib/python2.7/site-packages/nltk/data.py", line 801, in load
    opened_resource = _open(resource_url)
  File "/env/local/lib/python2.7/site-packages/nltk/data.py", line 919, in _open
    return find(path_, path + ['']).open()
  File "/env/local/lib/python2.7/site-packages/nltk/data.py", line 641, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource u'tokenizers/punkt/english.pickle' not found.  Please
  use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - '/root/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - u''
**********************************************************************
